micronaut:
  application:
    name: keyManagerGrpc

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/manager`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop

urls:
  apis:
    itau-erp: ${ITAU_ERP:`http://localhost:9091`}
